name: "StyleCI"

on: [push, pull_request]

jobs:
    Analyze:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v2
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.0"
                  extensions: curl
            - name: analyze code with StyleCI
              uses: ghostwriter/styleci-action@main
              with:
                  styleci_api_key: ${{ secrets.STYLECI_API_KEY }}
